### ISSUE TITLE
an advice

### ISSUE THREAD

**Issue by drogbababa** [nisrulz/screenshott#3]
this cant handle when an activity contains a surfaceview.

**Comment by nisrulz** [comment]
I haven't tested this, but would look into it.

**Comment by nisrulz** [comment]
@drogbababa I just tested it and you are right it does not work with SurfaceView. 

 I read up on why that would be the case and turns out it is because SurfaceView does not behave like other views ([Ref Link](https://stackoverflow.com/a/27824250/2745762))

There is probably a solution to this, but I haven't worked with OpenGL as much but will look into it because to solve this it looks like that would be the way to go forward.

**Comment by drogbababa** [comment]
Thank you for the answer.In my own demo,I solved this with your lib, but this need add some code in the view which extends SurfaceView.(an  self-defined view)
in the init(), I add 
**screenBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
screenCanvas = new Canvas(screenBitmap);**
and in the onDraw(), I add
**screenCanvas.drawArc(mRange, tmpAngle, sweepAngle, true,mArcPaint);** also in some other methods
I think maybe it should save a bitmap every time the onDraw() method works.
I am new to android,maybe my opinion is not correct ><

**Comment by nisrulz** [comment]
@drogbababa I have opened up a feature issue and closing this issue for now. Any more discussion should happen in the opened issue.
